array_width = 150
attr_fn_like_width = 0
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
chain_width = 150
color = "Always"
combine_control_expr = true
comment_width = 150
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021"
emit_mode = "Files"
empty_item_single_line = true
enum_discrim_align_threshold = 150
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Compressed"
fn_call_width = 150
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
hex_literal_case = "Preserve"
hide_parse_errors = false
tab_spaces = 2
indent_style = "Block"
inline_attribute_width = 150
normalize_comments = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
struct_field_align_threshold = 150
struct_lit_single_line = true
unstable_features = true
use_field_init_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true
